[package]
name = "rust_lib"
version = "0.1.0"
authors = ["Rasmus Tollund <rgt@cs.aau.dk>"]
license = "MIT"
edition = "2018"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type=["staticlib"]